AllCops:
  Exclude:
    - "bin/*"
    - "node_modules/**/*"

Style/SymbolArray:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - "config/**/*.rb"
    - "db/**/*.rb"

Style/PercentLiteralDelimiters:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - "config/**/*.rb"
    - "db/**/*.rb"

Style/ClassAndModuleChildren:
  Exclude:
    - "test/test_helper.rb"
